// <auto-generated />
using System;
using AeroTech.Ordering.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroTech.Ordering.Persistence.Migrations
{
    [DbContext(typeof(OrderingDbContext))]
    [Migration("20260807121658_InitialOrderingDomain")]
    partial class InitialOrderingDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Ordering")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroTech.Ordering.Domain.OperationAggregate.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CompensationPolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ExpectedExternalMessage")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("OrderRef")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OrderId");

                    b.Property<string>("Result")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ScopedItems")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("ScopedItems");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("TimeoutAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status", "NextRetryAtUtc");

                    b.HasIndex("Status", "TimeoutAtUtc");

                    b.HasIndex("OrderRef", "Type", "Status");

                    b.ToTable("Operations", "Ops");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnderLegalHold")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("RequiresReview")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Orders", "Ordering");
                });

            modelBuilder.Entity("AeroTech.Ordering.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Consumer")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("ReceivedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "Consumer");

                    b.HasIndex("ReceivedOn");

                    b.ToTable("InboxMessages", "dbo");
                });

            modelBuilder.Entity("AeroTech.Ordering.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn");

                    b.ToTable("OutboxMessages", "dbo");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OperationAggregate.Operation", b =>
                {
                    b.OwnsMany("AeroTech.Ordering.Domain.OperationAggregate.Entities.OperationStep", "StepHistory", b1 =>
                        {
                            b1.Property<Guid>("OperationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Seq")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Seq"));

                            b1.Property<DateTime?>("CompletedAtUtc")
                                .HasColumnType("datetime2(7)");

                            b1.Property<DateTime>("EnteredAtUtc")
                                .HasColumnType("datetime2(7)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("Outcome")
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.HasKey("OperationId", "Seq");

                            b1.ToTable("OperationSteps", "Ops");

                            b1.WithOwner()
                                .HasForeignKey("OperationId");
                        });

                    b.Navigation("StepHistory");
                });

            modelBuilder.Entity("AeroTech.Ordering.Domain.OrderAggregate.Order", b =>
                {
                    b.OwnsMany("AeroTech.Ordering.Domain.OrderAggregate.Entities.JourneyElement", "JourneyElements", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Id")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("JourneyElementId");

                            b1.Property<string>("Cabin")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)");

                            b1.Property<string>("MarriedGroup")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<string>("Rbd")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)");

                            b1.Property<int>("SequenceInJourney")
                                .HasColumnType("int");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("JourneyElements", "Ordering");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.FlightSegmentRef", "Flight", b2 =>
                                {
                                    b2.Property<Guid>("JourneyElementOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("JourneyElementId")
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<DateOnly>("ArrivalLocalDate")
                                        .HasColumnType("date")
                                        .HasColumnName("ArrivalLocalDate");

                                    b2.Property<TimeOnly>("ArrivalLocalTime")
                                        .HasColumnType("time(0)")
                                        .HasColumnName("ArrivalLocalTime");

                                    b2.Property<DateTime>("ArrivalUtc")
                                        .HasColumnType("datetime2(7)")
                                        .HasColumnName("ArrivalUtc");

                                    b2.Property<DateOnly>("DepartureLocalDate")
                                        .HasColumnType("date")
                                        .HasColumnName("DepartureLocalDate");

                                    b2.Property<TimeOnly>("DepartureLocalTime")
                                        .HasColumnType("time(0)")
                                        .HasColumnName("DepartureLocalTime");

                                    b2.Property<DateTime>("DepartureUtc")
                                        .HasColumnType("datetime2(7)")
                                        .HasColumnName("DepartureUtc");

                                    b2.Property<string>("Destination")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("nvarchar(8)")
                                        .HasColumnName("Destination");

                                    b2.Property<string>("DestinationTimeZoneId")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("DestinationTimeZoneId");

                                    b2.Property<string>("FlightNumber")
                                        .IsRequired()
                                        .HasMaxLength(16)
                                        .HasColumnType("nvarchar(16)")
                                        .HasColumnName("FlightNumber");

                                    b2.Property<string>("MarketingCarrier")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("nvarchar(8)")
                                        .HasColumnName("MarketingCarrier");

                                    b2.Property<string>("OperatingCarrier")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("nvarchar(8)")
                                        .HasColumnName("OperatingCarrier");

                                    b2.Property<string>("Origin")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("nvarchar(8)")
                                        .HasColumnName("Origin");

                                    b2.Property<string>("OriginTimeZoneId")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("OriginTimeZoneId");

                                    b2.HasKey("JourneyElementOrderId", "JourneyElementId");

                                    b2.HasIndex("MarketingCarrier", "FlightNumber", "DepartureLocalDate");

                                    b2.ToTable("JourneyElements", "Ordering");

                                    b2.WithOwner()
                                        .HasForeignKey("JourneyElementOrderId", "JourneyElementId");
                                });

                            b1.Navigation("Flight")
                                .IsRequired();
                        });

                    b.OwnsMany("AeroTech.Ordering.Domain.OrderAggregate.Entities.OrderItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Id")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("OrderItemId");

                            b1.Property<string>("CancellationReason")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<string>("JourneyRefs")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("JourneyRefs");

                            b1.Property<string>("ReplacesItem")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<string>("TravelerRef")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("TravelerId");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("OrderItems", "Ordering");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.OfferRef", "SourceOffer", b2 =>
                                {
                                    b2.Property<Guid>("OrderItemOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("OrderItemId")
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<DateTime>("OfferExpiryUtc")
                                        .HasColumnType("datetime2(7)")
                                        .HasColumnName("OfferExpiryUtc");

                                    b2.Property<string>("OfferId")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("OfferId");

                                    b2.Property<string>("OfferItemId")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("OfferItemId");

                                    b2.Property<string>("OfferOwner")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("OfferOwner");

                                    b2.HasKey("OrderItemOrderId", "OrderItemId");

                                    b2.ToTable("OrderItems", "Ordering");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemOrderId", "OrderItemId");
                                });

                            b1.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.PartnerDelivery", "Partner", b2 =>
                                {
                                    b2.Property<Guid>("OrderItemOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("OrderItemId")
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<string>("CommercialOwner")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("nvarchar(8)")
                                        .HasColumnName("PartnerCommercialOwner");

                                    b2.Property<string>("ControlTransferState")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("PartnerControlTransferState");

                                    b2.Property<string>("DeliveryOwner")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("nvarchar(8)")
                                        .HasColumnName("PartnerDeliveryOwner");

                                    b2.Property<string>("DisruptionResponsibility")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("PartnerDisruptionResponsibility");

                                    b2.Property<string>("ExternalItemReference")
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("PartnerExternalItemReference");

                                    b2.Property<string>("ExternalOrderReference")
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("PartnerExternalOrderReference");

                                    b2.Property<string>("PartnerStatus")
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("PartnerStatus");

                                    b2.Property<string>("PartnerStatusMappedTo")
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("PartnerStatusMappedTo");

                                    b2.Property<string>("ReconciliationReference")
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("PartnerReconciliationReference");

                                    b2.Property<string>("RefundResponsibility")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("PartnerRefundResponsibility");

                                    b2.Property<string>("ServicingAuthority")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("PartnerServicingAuthority");

                                    b2.Property<string>("SettlementBoundary")
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("PartnerSettlementBoundary");

                                    b2.HasKey("OrderItemOrderId", "OrderItemId");

                                    b2.ToTable("OrderItems", "Ordering");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemOrderId", "OrderItemId");
                                });

                            b1.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.PriceBreakdown", "Price", b2 =>
                                {
                                    b2.Property<Guid>("OrderItemOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("OrderItemId")
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("PriceCurrency");

                                    b2.Property<DateTime>("PricedAtUtc")
                                        .HasColumnType("datetime2(7)")
                                        .HasColumnName("PricedAtUtc");

                                    b2.Property<string>("PricingEngineVersion")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("PricingEngineVersion");

                                    b2.HasKey("OrderItemOrderId", "OrderItemId");

                                    b2.ToTable("OrderItems", "Ordering");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemOrderId", "OrderItemId");

                                    b2.OwnsMany("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.ChargeLine", "Lines", b3 =>
                                        {
                                            b3.Property<Guid>("OrderId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("OrderItemId")
                                                .HasColumnType("nvarchar(32)");

                                            b3.Property<int>("Seq")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int");

                                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b3.Property<int>("Seq"));

                                            b3.Property<string>("ChargeType")
                                                .IsRequired()
                                                .HasMaxLength(32)
                                                .HasColumnType("nvarchar(32)");

                                            b3.Property<string>("Code")
                                                .IsRequired()
                                                .HasMaxLength(64)
                                                .HasColumnType("nvarchar(64)");

                                            b3.Property<string>("Description")
                                                .HasMaxLength(256)
                                                .HasColumnType("nvarchar(256)");

                                            b3.Property<bool>("IsRefundable")
                                                .HasColumnType("bit");

                                            b3.Property<string>("TaxJurisdiction")
                                                .HasMaxLength(32)
                                                .HasColumnType("nvarchar(32)");

                                            b3.HasKey("OrderId", "OrderItemId", "Seq");

                                            b3.ToTable("ChargeLines", "Ordering");

                                            b3.WithOwner()
                                                .HasForeignKey("OrderId", "OrderItemId");

                                            b3.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.Money", "Amount", b4 =>
                                                {
                                                    b4.Property<Guid>("ChargeLineOrderId")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<string>("ChargeLineOrderItemId")
                                                        .HasColumnType("nvarchar(32)");

                                                    b4.Property<int>("ChargeLineSeq")
                                                        .HasColumnType("int");

                                                    b4.Property<decimal>("Amount")
                                                        .HasPrecision(19, 4)
                                                        .HasColumnType("decimal(19,4)")
                                                        .HasColumnName("Amount");

                                                    b4.Property<string>("Currency")
                                                        .IsRequired()
                                                        .HasMaxLength(3)
                                                        .HasColumnType("nvarchar(3)")
                                                        .HasColumnName("Currency");

                                                    b4.HasKey("ChargeLineOrderId", "ChargeLineOrderItemId", "ChargeLineSeq");

                                                    b4.ToTable("ChargeLines", "Ordering");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ChargeLineOrderId", "ChargeLineOrderItemId", "ChargeLineSeq");
                                                });

                                            b3.Navigation("Amount")
                                                .IsRequired();
                                        });

                                    b2.OwnsMany("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.ValueAllocation", "ValueAllocations", b3 =>
                                        {
                                            b3.Property<Guid>("OrderId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("OrderItemId")
                                                .HasColumnType("nvarchar(32)");

                                            b3.Property<int>("Seq")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int");

                                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b3.Property<int>("Seq"));

                                            b3.Property<string>("AllocationVersion")
                                                .IsRequired()
                                                .HasMaxLength(64)
                                                .HasColumnType("nvarchar(64)");

                                            b3.Property<string>("JourneyRef")
                                                .IsRequired()
                                                .HasMaxLength(32)
                                                .HasColumnType("nvarchar(32)")
                                                .HasColumnName("JourneyElementId");

                                            b3.Property<string>("ResidualPolicy")
                                                .IsRequired()
                                                .HasMaxLength(32)
                                                .HasColumnType("nvarchar(32)");

                                            b3.Property<string>("TravelerRef")
                                                .IsRequired()
                                                .HasMaxLength(32)
                                                .HasColumnType("nvarchar(32)")
                                                .HasColumnName("TravelerId");

                                            b3.HasKey("OrderId", "OrderItemId", "Seq");

                                            b3.ToTable("ValueAllocations", "Ordering");

                                            b3.WithOwner()
                                                .HasForeignKey("OrderId", "OrderItemId");

                                            b3.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.Money", "Amount", b4 =>
                                                {
                                                    b4.Property<Guid>("ValueAllocationOrderId")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<string>("ValueAllocationOrderItemId")
                                                        .HasColumnType("nvarchar(32)");

                                                    b4.Property<int>("ValueAllocationSeq")
                                                        .HasColumnType("int");

                                                    b4.Property<decimal>("Amount")
                                                        .HasPrecision(19, 4)
                                                        .HasColumnType("decimal(19,4)")
                                                        .HasColumnName("Amount");

                                                    b4.Property<string>("Currency")
                                                        .IsRequired()
                                                        .HasMaxLength(3)
                                                        .HasColumnType("nvarchar(3)")
                                                        .HasColumnName("Currency");

                                                    b4.HasKey("ValueAllocationOrderId", "ValueAllocationOrderItemId", "ValueAllocationSeq");

                                                    b4.ToTable("ValueAllocations", "Ordering");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ValueAllocationOrderId", "ValueAllocationOrderItemId", "ValueAllocationSeq");
                                                });

                                            b3.Navigation("Amount")
                                                .IsRequired();
                                        });

                                    b2.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.FxSnapshot", "Fx", b3 =>
                                        {
                                            b3.Property<Guid>("PriceBreakdownOrderItemOrderId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("PriceBreakdownOrderItemId")
                                                .HasColumnType("nvarchar(32)");

                                            b3.Property<DateTime>("CapturedAtUtc")
                                                .HasColumnType("datetime2(7)")
                                                .HasColumnName("FxCapturedAtUtc");

                                            b3.Property<string>("From")
                                                .IsRequired()
                                                .HasMaxLength(3)
                                                .HasColumnType("nvarchar(3)")
                                                .HasColumnName("FxFrom");

                                            b3.Property<decimal>("Rate")
                                                .HasPrecision(19, 4)
                                                .HasColumnType("decimal(19,8)")
                                                .HasColumnName("FxRate");

                                            b3.Property<string>("RateSource")
                                                .IsRequired()
                                                .HasMaxLength(64)
                                                .HasColumnType("nvarchar(64)")
                                                .HasColumnName("FxSource");

                                            b3.Property<string>("To")
                                                .IsRequired()
                                                .HasMaxLength(3)
                                                .HasColumnType("nvarchar(3)")
                                                .HasColumnName("FxTo");

                                            b3.HasKey("PriceBreakdownOrderItemOrderId", "PriceBreakdownOrderItemId");

                                            b3.ToTable("OrderItems", "Ordering");

                                            b3.WithOwner()
                                                .HasForeignKey("PriceBreakdownOrderItemOrderId", "PriceBreakdownOrderItemId");
                                        });

                                    b2.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.Money", "Total", b3 =>
                                        {
                                            b3.Property<Guid>("PriceBreakdownOrderItemOrderId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("PriceBreakdownOrderItemId")
                                                .HasColumnType("nvarchar(32)");

                                            b3.Property<decimal>("Amount")
                                                .HasPrecision(19, 4)
                                                .HasColumnType("decimal(19,4)")
                                                .HasColumnName("PriceTotal");

                                            b3.Property<string>("Currency")
                                                .IsRequired()
                                                .HasMaxLength(3)
                                                .HasColumnType("nvarchar(3)")
                                                .HasColumnName("PriceTotalCurrency");

                                            b3.HasKey("PriceBreakdownOrderItemOrderId", "PriceBreakdownOrderItemId");

                                            b3.ToTable("OrderItems", "Ordering");

                                            b3.WithOwner()
                                                .HasForeignKey("PriceBreakdownOrderItemOrderId", "PriceBreakdownOrderItemId");
                                        });

                                    b2.Navigation("Fx");

                                    b2.Navigation("Lines");

                                    b2.Navigation("Total")
                                        .IsRequired();

                                    b2.Navigation("ValueAllocations");
                                });

                            b1.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.ProductRef", "Product", b2 =>
                                {
                                    b2.Property<Guid>("OrderItemOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("OrderItemId")
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<string>("ProductCode")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("ProductCode");

                                    b2.Property<string>("ProductType")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("ProductType");

                                    b2.Property<string>("SourceSystemRef")
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("ProductSourceRef");

                                    b2.HasKey("OrderItemOrderId", "OrderItemId");

                                    b2.ToTable("OrderItems", "Ordering");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemOrderId", "OrderItemId");
                                });

                            b1.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.CreditAuthorityRef", "CreditAuthority", b2 =>
                                {
                                    b2.Property<Guid>("OrderItemOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("OrderItemId")
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<DateTime>("GrantedAtUtc")
                                        .HasColumnType("datetime2(7)")
                                        .HasColumnName("CreditAuthorityGrantedAtUtc");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("CreditAuthorityRef");

                                    b2.HasKey("OrderItemOrderId", "OrderItemId");

                                    b2.ToTable("OrderItems", "Ordering");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemOrderId", "OrderItemId");
                                });

                            b1.Navigation("CreditAuthority");

                            b1.Navigation("Partner");

                            b1.Navigation("Price")
                                .IsRequired();

                            b1.Navigation("Product")
                                .IsRequired();

                            b1.Navigation("SourceOffer")
                                .IsRequired();
                        });

                    b.OwnsMany("AeroTech.Ordering.Domain.OrderAggregate.Entities.PaymentRecord", "Payments", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Id")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("PaymentRecordId");

                            b1.Property<string>("Fop")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("FormOfPayment");

                            b1.Property<bool>("IsUnderDispute")
                                .HasColumnType("bit");

                            b1.Property<string>("PayerRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<DateTime>("RecordedAtUtc")
                                .HasColumnType("datetime2(7)");

                            b1.Property<string>("RequestRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("PaymentRequestRef");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("PaymentRecords", "Ordering");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsMany("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.PaymentAllocation", "Allocations", b2 =>
                                {
                                    b2.Property<Guid>("OrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("PaymentRecordId")
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<string>("ItemRef")
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("OrderItemId");

                                    b2.HasKey("OrderId", "PaymentRecordId", "ItemRef");

                                    b2.ToTable("PaymentAllocations", "Ordering");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderId", "PaymentRecordId");

                                    b2.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.Money", "Amount", b3 =>
                                        {
                                            b3.Property<Guid>("PaymentAllocationOrderId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("PaymentAllocationPaymentRecordId")
                                                .HasColumnType("nvarchar(32)");

                                            b3.Property<string>("PaymentAllocationItemRef")
                                                .HasColumnType("nvarchar(32)");

                                            b3.Property<decimal>("Amount")
                                                .HasPrecision(19, 4)
                                                .HasColumnType("decimal(19,4)")
                                                .HasColumnName("Amount");

                                            b3.Property<string>("Currency")
                                                .IsRequired()
                                                .HasMaxLength(3)
                                                .HasColumnType("nvarchar(3)")
                                                .HasColumnName("Currency");

                                            b3.HasKey("PaymentAllocationOrderId", "PaymentAllocationPaymentRecordId", "PaymentAllocationItemRef");

                                            b3.ToTable("PaymentAllocations", "Ordering");

                                            b3.WithOwner()
                                                .HasForeignKey("PaymentAllocationOrderId", "PaymentAllocationPaymentRecordId", "PaymentAllocationItemRef");
                                        });

                                    b2.Navigation("Amount")
                                        .IsRequired();
                                });

                            b1.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("PaymentRecordOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("PaymentRecordId")
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(19, 4)
                                        .HasColumnType("decimal(19,4)")
                                        .HasColumnName("Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("Currency");

                                    b2.HasKey("PaymentRecordOrderId", "PaymentRecordId");

                                    b2.ToTable("PaymentRecords", "Ordering");

                                    b2.WithOwner()
                                        .HasForeignKey("PaymentRecordOrderId", "PaymentRecordId");
                                });

                            b1.OwnsOne("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.FxSnapshot", "Fx", b2 =>
                                {
                                    b2.Property<Guid>("PaymentRecordOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("PaymentRecordId")
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<DateTime>("CapturedAtUtc")
                                        .HasColumnType("datetime2(7)")
                                        .HasColumnName("FxCapturedAtUtc");

                                    b2.Property<string>("From")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("FxFrom");

                                    b2.Property<decimal>("Rate")
                                        .HasPrecision(19, 4)
                                        .HasColumnType("decimal(19,8)")
                                        .HasColumnName("FxRate");

                                    b2.Property<string>("RateSource")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("FxSource");

                                    b2.Property<string>("To")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("FxTo");

                                    b2.HasKey("PaymentRecordOrderId", "PaymentRecordId");

                                    b2.ToTable("PaymentRecords", "Ordering");

                                    b2.WithOwner()
                                        .HasForeignKey("PaymentRecordOrderId", "PaymentRecordId");
                                });

                            b1.Navigation("Allocations");

                            b1.Navigation("Amount")
                                .IsRequired();

                            b1.Navigation("Fx");
                        });

                    b.OwnsMany("AeroTech.Ordering.Domain.OrderAggregate.Entities.TimeLimit", "TimeLimits", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Id")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("TimeLimitId");

                            b1.Property<string>("AppliesTo")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("AppliesTo");

                            b1.Property<DateTime>("DueAtUtc")
                                .HasColumnType("datetime2(7)");

                            b1.Property<int>("ExtensionCount")
                                .HasColumnType("int");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.HasKey("OrderId", "Id");

                            b1.HasIndex("Status", "DueAtUtc")
                                .HasFilter("[Status] = 'Active'");

                            b1.ToTable("TimeLimits", "Ordering");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsMany("AeroTech.Ordering.Domain.OrderAggregate.Entities.Traveler", "Travelers", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Id")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("TravelerId");

                            b1.Property<string>("AssociatedAdult")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<string>("CustomerRef")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<DateOnly?>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<string>("Ptc")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("Travelers", "Ordering");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsMany("AeroTech.Ordering.Domain._Shared.ValueObjects.IdentityDocument", "Documents", b2 =>
                                {
                                    b2.Property<Guid>("OrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("TravelerId")
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<int>("Seq")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Seq"));

                                    b2.Property<string>("DocType")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<DateOnly?>("Expiry")
                                        .HasColumnType("date");

                                    b2.Property<string>("IssuingCountry")
                                        .HasMaxLength(8)
                                        .HasColumnType("nvarchar(8)");

                                    b2.Property<string>("Nationality")
                                        .HasMaxLength(8)
                                        .HasColumnType("nvarchar(8)");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)");

                                    b2.HasKey("OrderId", "TravelerId", "Seq");

                                    b2.ToTable("TravelerDocuments", "Ordering");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderId", "TravelerId");
                                });

                            b1.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.TravelerName", "Name", b2 =>
                                {
                                    b2.Property<Guid>("TravelerOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("TravelerId")
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<string>("Given")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("Given");

                                    b2.Property<string>("GivenLocal")
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("GivenLocal");

                                    b2.Property<string>("Surname")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("Surname");

                                    b2.Property<string>("SurnameLocal")
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("SurnameLocal");

                                    b2.Property<string>("Title")
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("Title");

                                    b2.HasKey("TravelerOrderId", "TravelerId");

                                    b2.ToTable("Travelers", "Ordering");

                                    b2.WithOwner()
                                        .HasForeignKey("TravelerOrderId", "TravelerId");
                                });

                            b1.Navigation("Documents");

                            b1.Navigation("Name")
                                .IsRequired();
                        });

                    b.OwnsMany("AeroTech.Ordering.Domain.OrderAggregate.Entities.TravelerJourneySegment", "Segments", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("TravelerRef")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("TravelerId");

                            b1.Property<string>("JourneyRef")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("JourneyElementId");

                            b1.Property<string>("DeliveryStatus")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<string>("Hold")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("InventoryHoldRef");

                            b1.Property<string>("SegmentStatus")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.HasKey("OrderId", "TravelerRef", "JourneyRef");

                            b1.ToTable("TravelerJourneySegments", "Ordering");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.DeliveryUnitRef", "DeliveryRef", b2 =>
                                {
                                    b2.Property<Guid>("TravelerJourneySegmentOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("TravelerJourneySegmentTravelerRef")
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<string>("TravelerJourneySegmentJourneyRef")
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<string>("DeliveryRecordNumber")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("DeliveryRecordNumber");

                                    b2.Property<DateTime>("MirroredAtUtc")
                                        .HasColumnType("datetime2(7)")
                                        .HasColumnName("MirroredAtUtc");

                                    b2.Property<int>("UnitNumber")
                                        .HasColumnType("int")
                                        .HasColumnName("DeliveryUnitNumber");

                                    b2.HasKey("TravelerJourneySegmentOrderId", "TravelerJourneySegmentTravelerRef", "TravelerJourneySegmentJourneyRef");

                                    b2.ToTable("TravelerJourneySegments", "Ordering");

                                    b2.WithOwner()
                                        .HasForeignKey("TravelerJourneySegmentOrderId", "TravelerJourneySegmentTravelerRef", "TravelerJourneySegmentJourneyRef");
                                });

                            b1.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.SeatAssignment", "Seat", b2 =>
                                {
                                    b2.Property<Guid>("TravelerJourneySegmentOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("TravelerJourneySegmentTravelerRef")
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<string>("TravelerJourneySegmentJourneyRef")
                                        .HasColumnType("nvarchar(32)");

                                    b2.Property<DateTime>("AssignedAtUtc")
                                        .HasColumnType("datetime2(7)")
                                        .HasColumnName("SeatAssignedAtUtc");

                                    b2.Property<string>("SeatNumber")
                                        .IsRequired()
                                        .HasMaxLength(16)
                                        .HasColumnType("nvarchar(16)")
                                        .HasColumnName("SeatNumber");

                                    b2.HasKey("TravelerJourneySegmentOrderId", "TravelerJourneySegmentTravelerRef", "TravelerJourneySegmentJourneyRef");

                                    b2.ToTable("TravelerJourneySegments", "Ordering");

                                    b2.WithOwner()
                                        .HasForeignKey("TravelerJourneySegmentOrderId", "TravelerJourneySegmentTravelerRef", "TravelerJourneySegmentJourneyRef");
                                });

                            b1.Navigation("DeliveryRef");

                            b1.Navigation("Seat");
                        });

                    b.OwnsMany("AeroTech.Ordering.Domain.OrderAggregate.ValueObjects.OrderHistoryEntry", "History", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("SequenceNo")
                                .HasColumnType("bigint");

                            b1.Property<string>("CausationId")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("Channel")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("ChannelCode");

                            b1.Property<string>("CommandName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("CorrelationId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<DateTime>("OccurredAtUtc")
                                .HasColumnType("datetime2(7)");

                            b1.Property<long>("ResultingAggregateVersion")
                                .HasColumnType("bigint");

                            b1.HasKey("OrderId", "SequenceNo");

                            b1.ToTable("OrderHistory", "Audit");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.ActorRef", "Actor", b2 =>
                                {
                                    b2.Property<Guid>("OrderHistoryEntryOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<long>("OrderHistoryEntrySequenceNo")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ActorType")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("ActorType");

                                    b2.Property<bool>("HasAirlineOverride")
                                        .HasColumnType("bit")
                                        .HasColumnName("ActorHasAirlineOverride");

                                    b2.Property<string>("OfficeId")
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("ActorOfficeId");

                                    b2.Property<string>("SellerId")
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("ActorSellerId");

                                    b2.Property<string>("UserId")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("ActorUserId");

                                    b2.HasKey("OrderHistoryEntryOrderId", "OrderHistoryEntrySequenceNo");

                                    b2.ToTable("OrderHistory", "Audit");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderHistoryEntryOrderId", "OrderHistoryEntrySequenceNo");
                                });

                            b1.Navigation("Actor")
                                .IsRequired();
                        });

                    b.OwnsMany("AeroTech.Ordering.Domain._Shared.ValueObjects.ContactPoint", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Seq")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Seq"));

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("bit");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.HasKey("OrderId", "Seq");

                            b1.ToTable("ContactPoints", "Ordering");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.SalesContext", "SalesContext", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Channel")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("ChannelCode");

                            b1.Property<string>("OfficeId")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("OfficeId");

                            b1.Property<string>("PointOfSale")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("PointOfSale");

                            b1.Property<string>("SaleCurrency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("SaleCurrency");

                            b1.Property<string>("SellerId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("SellerId");

                            b1.Property<DateTime>("SoldAtUtc")
                                .HasColumnType("datetime2(7)")
                                .HasColumnName("SoldAtUtc");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "Ordering");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("AeroTech.Ordering.Domain._Shared.ValueObjects.ActorRef", "CreatedBy", b2 =>
                                {
                                    b2.Property<Guid>("SalesContextOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ActorType")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("CreatedByActorType");

                                    b2.Property<bool>("HasAirlineOverride")
                                        .HasColumnType("bit")
                                        .HasColumnName("CreatedByHasAirlineOverride");

                                    b2.Property<string>("OfficeId")
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("CreatedByOfficeId");

                                    b2.Property<string>("SellerId")
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("CreatedBySellerId");

                                    b2.Property<string>("UserId")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("CreatedByUserId");

                                    b2.HasKey("SalesContextOrderId");

                                    b2.ToTable("Orders", "Ordering");

                                    b2.WithOwner()
                                        .HasForeignKey("SalesContextOrderId");
                                });

                            b1.Navigation("CreatedBy")
                                .IsRequired();
                        });

                    b.Navigation("Contacts");

                    b.Navigation("History");

                    b.Navigation("Items");

                    b.Navigation("JourneyElements");

                    b.Navigation("Payments");

                    b.Navigation("SalesContext")
                        .IsRequired();

                    b.Navigation("Segments");

                    b.Navigation("TimeLimits");

                    b.Navigation("Travelers");
                });
#pragma warning restore 612, 618
        }
    }
}
